Add login page, auth request logic
Reactivnye-Enoty-Na-Lyzhan/among-us pull request #13
Opened 2023-04-01 18:55 UTC by tzhovtyi

### Какую задачу решаем
1. Верстка страницы входа
2. Логика запросов для входа

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/87607555/229309198-ef98dc52-6e12-4dd6-bd66-c400c6082227.png)

2023-04-01 19:19 UTC, MikeDevice requested changes

2023-04-01 19:19 UTC, MikeDevice commented on packages/client/src/api/auth.ts
> +    console.log(data);
логи нам нужны? если нет, то удали

2023-04-01 19:19 UTC, MikeDevice commented on packages/client/src/components/LoginPage/LoginPage.tsx
> +                  console.log(values);
лог

2023-04-01 19:19 UTC, MikeDevice commented on packages/client/src/controllers/auth.ts
> +export async function signIn(data: signInData, setErrorMessage: Dispatch<SetStateAction<string>> ) {
это какой-то рокет-саинс прям. у тебя есть метод, который вроде как полностью самостоятельный, но при этом он принимает функцию управления стейтом компонента. То есть ты прям завязываешь эту функцию на компонент (не обязательно на этот).

Это не очень правильный подход. Эта функция не должна знать про реакт. Её задача -- логинить. Рисовать ошибку, причём в конкретном компоненте -- не её обязанность

2023-04-01 19:19 UTC, MikeDevice commented on packages/client/src/controllers/auth.ts
> +export async function signIn(data: signInData, setErrorMessage: Dispatch<SetStateAction<string>> ) {
Помимо этого, есть ещё и другие вопросы.

1. Функция просто логирует статус выполнения просто в консоль. Пользователь вообще никак не понимает, что происходит.
2. Функция ассинхронная. Пока она отрабатывает, интерфейс так же никак не отображает своё состояние.

2023-04-01 19:19 UTC, MikeDevice commented on packages/client/src/controllers/auth.ts
> +            } catch(e:any) {
ошибка и так any по дефолту же, нет?

2023-04-01 19:19 UTC, MikeDevice commented on packages/client/src/controllers/auth.ts
> +        if(res.status === 401) {
хмм. мне кажется, не совсем правильно, что статус не равный 200, он не вызывает исключение. Если бы всё, что не 200, улетало в catch, то столько ифаков не пришлось бы писать.

```js
try {
  const res = await signInAPI(data);
  const response = await res.json();
  // показать юзеру успех
} catch (err) {
  if (!err?.status) {
    // какая-то непредвиденная ошибка, не связанная с работой АПИ
    // показать глобальную ошибку
    return;
  }

  const errorText = ErrorsHash[res.status];
  // показать ошибку
}
```

2023-04-02 08:36 UTC, artiquanta approved these changes
Одно можно лучше + замечания от Михаила)

2023-04-02 08:36 UTC, artiquanta commented on packages/client/src/components/LoginPage/LoginPage.css
> +    display: grid;
**Можно лучше**: если нужно просто выравнить элемент по центру, то лучше использовать flex и justify-content / align-items, так как в данном случае сетка по сути и не используется

2023-04-02 11:40 UTC, tzhovtyi commented on packages/client/src/components/LoginPage/LoginPage.css
> +    display: grid;
Да, это просто экономит одну строчку кода. Есть какие-то негативные эффекты от этого?

2023-04-02 11:55 UTC, MikeDevice commented on packages/client/src/components/LoginPage/LoginPage.css
> +    display: grid;
Смотри. Я могу тут провести такую аналогию. Есть молоток, и есть плоскогубцы. Что тем, что этим можно забить гвоздь, или разрезать провод. Однако в первом случае проще использовать молоток, а плоскогубцы -- во втором. Почему? Потому что это их прямое назначение.

Так и тут. Разные способы выравниваний создавались с конкретной целью. Гриды -- чтобы делать каскад страницы, а флексы -- для выравниваний внутри элементов. Потому @artiquanta об этом и говорит.

Я не вижу ничего страшного в использвании гридов тут, просто надо понимать, что они создавались не для этих целей

2023-04-02 12:08 UTC, tzhovtyi commented on packages/client/src/controllers/auth.ts
> +            } catch(e:any) {
unknown, поэтому ошибку ts будет кидать

2023-04-02 12:22 UTC, tzhovtyi commented on packages/client/src/components/LoginPage/LoginPage.css
> +    display: grid;
Принято, спасибо!

2023-04-02 20:14 UTC, MikeDevice approved these changes
Задача минимум: избавиться от самовызывающей функции.
Максимум: убрать их комопнента бизнес-логику логина

2023-04-02 20:14 UTC, MikeDevice commented on packages/client/src/components/LoginPage/LoginPage.tsx
> +    })();
это не круто, что ты самовызывающую функцию пишешь. Что мешает тебе handleSubmit сделать асинхронной? Ну или юзай промисы.

Вообще в идеале, реакт-компонент -- не место для таких вызовов. Реакт должен кидать только экшн "Кнопка нажата" и тд. и тп. А вот всё такое должно рулиться из контроллера

2023-04-11 10:24 UTC, merged