Добавить экран начала игры
Reactivnye-Enoty-Na-Lyzhan/among-us pull request #18
Opened 2023-04-06 16:25 UTC by artiquanta

### Какую задачу решаем
Добавляем экран начала игры

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/93656865/230439314-0f31a621-0798-460a-9436-cafff468fa1c.png)

2023-04-09 08:29 UTC, Issayev approved these changes
Все работает. Хорошо структурировано

2023-04-10 12:22 UTC, MikeDevice requested changes
1. компоненты очень большие
2. много где не используется TypeScript или нарушаются типизации (`as` и всё вот это вот)
3. Не гуляй с Приттером по проекту в рамках других задач.

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/ErrorBoundary/ErrorBoundary.css
> +  background: #010318;
ребят, это не круто. я уже который ПР смотрю и вижу, что в файлах меняется форматирование. Это не круто. Если напрягает форматирование, сделайте задачу, и в рамках её поправьте форматирование во **всём** проекте. А то смотреть каждый раз на то, как вы параллельно с основной задачей её меняете -- вообще не ок.

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/ErrorBoundary/ErrorBoundary.css
> +  background: #010318;
И сделайте так, чтобы у всех в IDE было настроено одинаковое форматирование, чтоб вы все писали в едином стиле.

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/ErrorBoundary/ErrorBoundary.css
> +  background: #010318;
Вам же самим не ок смотреть на километровые диффы в каждом ПР, потому что непонятно, что изменилось по задаче, а что "просто так"

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/GamePage.tsx
> +  const hasActiveGame = false;
этот параметр откуда-то потом будет приходить?

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/GamePage.tsx
> +  const isGameEnded = false;
и этот?

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/ProtectedGame/ProtectedGame.tsx
> +  return <>{isStarted ? <Outlet /> : <Navigate to=".." />}</>;
не совсем понял:
1. что это за компонент?
2. ты же в компоненте Game проверяешь статус игры, начата она или закончена. Зачем тогда тут проверять?
3. Почему Navigate на `..`? Это какой-то странный подход, так как он нестабильный. Обоснуешь, почему так решил? 
4. Тут не нужен `Fragment`

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.css
> +  width: 87.9vw;
выглядит как баг. ты уверен, такая ширина не развалится на 4к мониторе или на маленьком Макбуке?

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.css
> +  margin: 29.86vh 0 0;
и вот тут тоже

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/utils/plural.ts
> +};
есть либы, которое в такое умеют, но ок)

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/utils/plural.ts
> +};
https://github.com/plurals/pluralize

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/utils/gameParams.ts
> +export type GameParamsType = {
Кстати, почему ты не используешь TypeScript?

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/utils/gameParams.ts
> +export const gameNamePattern = /^[0-9a-zA-Zа-яА-ЯёЁ-]*$/i;
Имя может быть пустым? Данная регулярка пропускает пустую строку.

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +        onClick={handleExitGame}>
это должна быть ссылка `Link (из react-router)`, а не кнопка. https://htmlacademy.ru/blog/html/links-or-buttons

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +    counter > 0 && setTimeout(() => setCounter(counter - 1), 1000);
это очень плохой подход -- писать ифаки в таком виде. Не настаиваю на изменениях, но коммьюнити такое не любит.

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +    counter > 0 && setTimeout(() => setCounter(counter - 1), 1000);
2. Если изменится `counter`, то этот setTimeout не удалится, и к нему добавится новый. Это потенциальная утечка по памяти

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +    navigate('..');
это не круто навигировать так. Покажешь, где ты увидел такое? До тебя я такого не встречал.

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +  const pluralInterval = pluralRules.select(gameSettings.interval);
не размазывай логику. вынеси это в хелпер. Это не должно быть во вью

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +          </li>
Копипаста: сделай циклом

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/CreateGame/CreateGame.tsx
> +            <ul className="create-game__params">
слишком огромный компонент вышел. Разбей на мелкие. Вот так в switch вставлять разные компоненты -- вообще антипаттерн.

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/CreateGame/CreateGame.tsx
> +      <Link to=".." className="create-game__leave-game">
тот же самый вопрос про навигацию

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/CreateGame/GameParam/GameParam.tsx
> +            onClick={() => onIncrease(name, inputValue, min, max)}>
инлайнить функции не очень хорошо. ты всё обернул в memo, но при этом передаёшь инлайновые функции. 

В данном примере особых проблем нет, но в целом это не ок

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/FinalPreparing/ColorButton/ColorButton.tsx
> +    onSelect(color as keyof SuitColorsType);
если приходится делать приведение типов, значит где-то что-то идёт не так. Почему color -- это просто string?

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/FinalPreparing/FinalPreparing.tsx
> +  setTimeout(() => setUsedColors(colors => ({ ...colors, white: true })), 5000);
каждый рендер создаёшь новый таймаут. если это временное, как ты пишешь -- ок, но не делай так.

2023-04-10 12:22 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/HowToPlay/HowToPlay.tsx
> +      <button className="howtoplay__go-back" onClick={() => navigate(-1)}>
куда мы попадём? на предыдущую страницу? лучше юзать `history.back`. Так ты приносишь много неявности

2023-04-10 13:16 UTC, artiquanta commented on packages/client/src/components/ErrorBoundary/ErrorBoundary.css
> +  background: #010318;
> Вам же самим не ок смотреть на километровые диффы в каждом ПР, потому что непонятно, что изменилось по задаче, а что "просто так"

Спасибо! Полностью согласен, моя вина (использовал yarn format, но не посмотрел внесённые изменения перед коммитом, да и после). Вроде как, все используют единые параметры форматировано. Но, похоже, что что-то пошло не так.

2023-04-10 13:16 UTC, artiquanta commented on packages/client/src/components/GamePage/GamePage.tsx
> +  const hasActiveGame = false;
> этот параметр откуда-то потом будет приходить?

На данный момент из воздуха, далее из хранилища

2023-04-10 13:17 UTC, artiquanta commented on packages/client/src/components/GamePage/GamePage.tsx
> +  const isGameEnded = false;
Аналогично предыдущему

2023-04-10 13:38 UTC, artiquanta commented on packages/client/src/components/GamePage/ProtectedGame/ProtectedGame.tsx
> +  return <>{isStarted ? <Outlet /> : <Navigate to=".." />}</>;
1. Подобие простого HOK, пока не завезли redux.
2. Чтобы не было возможности открыть вложенные страницы. По типу /game/await
3. Стабильность проверить не могу. Использовал, чтобы путь для навигации брать относительно родительского компонента, где используется этот HOK. Альтернатива - /game (от root'а проекта). Подскажи, пожалуйста, как лучше, если мне нужно с одного вложенного маршрута отправить пользователя на другой вложенный маршрут общего родительского маршрута?

2023-04-10 13:44 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.css
> +  width: 87.9vw;
> выглядит как баг. ты уверен, такая ширина не развалится на 4к мониторе или на маленьком Макбуке?

Проверить смог только от 1280 до ~3к. Ширина фактически ограничена в 1280px, чтобы избежать сильно большой ширины макета. Макбук Air 11 года - в 1366px шириной (примерно). Для него идеально зайдёт. Viewport у прошек до 1500 шириной +-.

2023-04-10 13:49 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.css
> +  margin: 29.86vh 0 0;
Напротив, такое решение позволит отобразить данный элемент с сохранением пропорций из макета.

2023-04-10 13:50 UTC, artiquanta commented on packages/client/src/utils/plural.ts
> +};
У нас же вроде как "минимум либ, больше сами"?) Спасибо!

2023-04-10 13:50 UTC, artiquanta commented on packages/client/src/utils/gameParams.ts
> +export type GameParamsType = {
> Кстати, почему ты не используешь TypeScript?

Уточни?

2023-04-10 13:54 UTC, artiquanta commented on packages/client/src/utils/gameParams.ts
> +export const gameNamePattern = /^[0-9a-zA-Zа-яА-ЯёЁ-]*$/i;
> Имя может быть пустым? Данная регулярка пропускает пустую строку.
Микро недоработка, но проверка на min-max осуществляется непосредственно при валидации

2023-04-10 14:01 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +        onClick={handleExitGame}>
> это должна быть ссылка `Link (из react-router)`, а не кнопка. https://htmlacademy.ru/blog/html/links-or-buttons

По задумке - нет. В первую очередь, нужно или завершить подбор игры, или отменить ранее созданную игру. И только если всё проходит успешно - выбросить пользователя со страницы. Логики сейчас нет. Появится в рамках следующей задачи.

2023-04-10 14:02 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +    counter > 0 && setTimeout(() => setCounter(counter - 1), 1000);
Понял, принял!

2023-04-10 14:13 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +    navigate('..');
Это попытки проброса на родителя, без явного указания пути от рута. Подскажи тогда, пожалуйста, как правильней будет: писать полный путь от рута к нужному компоненту (или другому вложенному роуту), прокидывать пропсами? 

Т.е. если представить, что у нас game находится по пути /smth1/smth2/game, тогда путь для навигации к его вложенному маршруту нужно вот так указывать /smth1/smth2/game/await?

2023-04-10 14:28 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +          </li>
> Копипаста: сделай циклом

Даже если эти параметры не изменятся? Придётся объект с настройками усложнять, делать проверки на наличие plural, подкидывая его тип?

2023-04-10 14:29 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/CreateGame/CreateGame.tsx
> +      <Link to=".." className="create-game__leave-game">
> тот же самый вопрос про навигацию

Ответил выше

2023-04-10 14:52 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/HowToPlay/HowToPlay.tsx
> +      <button className="howtoplay__go-back" onClick={() => navigate(-1)}>
> куда мы попадём? на предыдущую страницу? лучше юзать `history.back`. Так ты приносишь много неявности

Если не ошибаюсь, в v6 избавляются от useHistory. И вместо back и т.д. предлагают использовать как раз такое решение? [v6](https://reactrouter.com/en/main/upgrading/v5#use-usenavigate-instead-of-usehistory)

2023-04-10 14:53 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/FinalPreparing/FinalPreparing.tsx
> +  setTimeout(() => setUsedColors(colors => ({ ...colors, white: true })), 5000);
> каждый рендер создаёшь новый таймаут. если это временное, как ты пишешь -- ок, но не делай так.

Временно, пока мультиплеера нет. Этот конкретный setTimeout забыл в cdm засунуть.

2023-04-10 14:55 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/FinalPreparing/ColorButton/ColorButton.tsx
> +    onSelect(color as keyof SuitColorsType);
> если приходится делать приведение типов, значит где-то что-то идёт не так. Почему color -- это просто string?

Изначальный массив с "цветами" - string[].
Такой вариант допустим?
export type SuitColorsType = {
  [k in typeof suitsColors[number]]: boolean;
}

export const suitsColors = [
  'white',
  'red',
] as const;

2023-04-11 08:13 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +    counter > 0 && setTimeout(() => setCounter(counter - 1), 1000);
По 2. Изначально, в этом и суть. Что при изменении counter'а - (если тот больше нуля), вызывается новый setTimeout, который в дальнейшем и уменьшит значение counter.

2023-04-11 09:40 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.css
> +  margin: 29.86vh 0 0;
тут я больше говорил о том, почему не 30. Что такие дроби выглядят весьма странно

2023-04-11 09:41 UTC, MikeDevice commented on packages/client/src/utils/gameParams.ts
> +export type GameParamsType = {
про `no-inferrable-types` претензий нет. У тебя есть файлы, где огромные json лежат, и типы в них не описаны.

2023-04-11 09:42 UTC, MikeDevice commented on packages/client/src/utils/gameParams.ts
> +export type GameParamsType = {
По правилам вашего курса, это весомый повод, чтобы поставить reject

2023-04-11 09:50 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.css
> +  margin: 29.86vh 0 0;
> тут я больше говорил о том, почему не 30. Что такие дроби выглядят весьма странно

Соответствие макету.

2023-04-11 09:54 UTC, artiquanta commented on packages/client/src/utils/gameParams.ts
> +export type GameParamsType = {
> По правилам вашего курса, это весомый повод, чтобы поставить reject

Было пропущено только в некоторых местах, но не везде, это моя ошибка, согласен. А файлы все эти через пару канут в лету

2023-04-11 10:04 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +        onClick={handleExitGame}>
проблема в том, что я не знаю задумку) короче идея моя в том, что ссылки не должны быть кнопками, а кнопки -- ссылками. В ссылке выше объяснение, почему. Реши что тебе надо, и тогда юзай. Если что, onClick на ссылку вешать можно тоже

2023-04-11 10:05 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +    counter > 0 && setTimeout(() => setCounter(counter - 1), 1000);
ух ты ж. я понял тебя, но это прям сложно читать. в плане, видишь, я не понял твоей идеи.

2023-04-11 10:10 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +    navigate('..');
да это я понял. и в целом, я не против этой идеи, просто есть переживание того, что когда приложение становится более сложным, то это становится сильно сложно поддерживать.

Пример.
У тебя есть страница результатов игры `/game/results`, и на этой странице ты делаешь `navigate(..)`, который кинет тебя на `/game`. Тут всё круто. Но однажды приходит менеджер и говорит, что мы хотим всему миру транслировать результаты игры (смотреть на статистику), в отрыве от самой игры, потому нам надо заходить на эту страницу, не заходя на страницу игры. Ты что делаешь? Настраиваешь роутер так, чтобы компонент результатов рисовался ещё и на `/results-promo-page`. И что произойдёт? На этой странице будет `navigate(..)`, который отправит тебя не на `/game`, а в корень.

Пример высосан из пальца, но идея, думаю, ясна. Я не против этого, просто оберегаю, и предлагаю быть с этим аккуратным.

2023-04-11 10:12 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +          </li>
в целом да. дело твоё на самом деле. Настаивать не буду. но как по мне, это не очень. Ты же реально копи-пастишь теги и их классы. Меняется лишь содержимое. Если придётся в span, добавить вложенный тег, придётся делать это триды

2023-04-11 10:14 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/HowToPlay/HowToPlay.tsx
> +      <button className="howtoplay__go-back" onClick={() => navigate(-1)}>
хммм. крутяк. не знал. спасибо!

2023-04-11 10:16 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/FinalPreparing/ColorButton/ColorButton.tsx
> +    onSelect(color as keyof SuitColorsType);
Подожди, а разве не достаточно просто сделать?

```diff
type Props = {
- color: string;
+ color: SuitColorsType;
  selected: boolean;
  disabled: boolean;
  onSelect: (color: keyof SuitColorsType) => void;
};
```

2023-04-11 10:17 UTC, MikeDevice commented
Вижу коммит, но ты не запросил ревью изменений. Ещё что-то будет?

2023-04-11 10:20 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +    navigate('..');
> да это я понял. и в целом, я не против этой идеи, просто есть переживание того, что когда приложение становится более сложным, то это становится сильно сложно поддерживать.
> 
> Пример. У тебя есть страница результатов игры `/game/results`, и на этой странице ты делаешь `navigate(..)`, который кинет тебя на `/game`. Тут всё круто. Но однажды приходит менеджер и говорит, что мы хотим всему миру транслировать результаты игры (смотреть на статистику), в отрыве от самой игры, потому нам надо заходить на эту страницу, не заходя на страницу игры. Ты что делаешь? Настраиваешь роутер так, чтобы компонент результатов рисовался ещё и на `/results-promo-page`. И что произойдёт? На этой странице будет `navigate(..)`, который отправит тебя не на `/game`, а в корень.
> 
> Пример высосан из пальца, но идея, думаю, ясна. Я не против этого, просто оберегаю, и предлагаю быть с этим аккуратным.

Спасибо за пример и разъяснение, буду учитывать при выборе способа навигации! А по текущему: нынесуществующие вложенные компоненты так и останутся исключительно вложенными маршрутами для Game (если конечно не появится менеджер с "уникальной" просьбой от заказчика :) ). Предполагаю, что тут есть ещё альтернатива. Приходит менеджер и говорит, а давай-ка game закинем куда-нибудь глубже, в /presentation/game. Тогда, получается, что столкнёмся с 404, так как /game не будет существовать.

2023-04-11 10:26 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +          </li>
> в целом да. дело твоё на самом деле. Настаивать не буду. но как по мне, это не очень. Ты же реально копи-пастишь теги и их классы. Меняется лишь содержимое. Если придётся в span, добавить вложенный тег, придётся делать это трижды

Я понимаю, что ты прав и с учётом "будущих возможностей" - это тоже не самый лучший вариант. Но вот если учитывать, что объект с настройками игры может быть огромным, то получается, сначала нужно будет пройтись по объекту, отфильтровать его на соответствие параметрам для вывода пользователю, получить соответствующие заголовки, просчитать и отобразить plural, если он нужен этому параметру. А если брать в расчёт, что параметры будут выводиться именно эти, то возникает ощущение, что появится лишнее усложнение логики.

2023-04-11 11:05 UTC, artiquanta commented
> Вижу коммит, но ты не запросил ревью изменений. Ещё что-то будет?

Извини, задержался! Запросил ревью

2023-04-11 11:24 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/FinalPreparing/ColorButton/ColorButton.tsx
> +    onSelect(color as keyof SuitColorsType);
> Подожди, а разве не достаточно просто сделать?
> 
> ```diff
> type Props = {
> - color: string;
> + color: SuitColorsType;
>   selected: boolean;
>   disabled: boolean;
>   onSelect: (color: keyof SuitColorsType) => void;
> };
> ```

Вроде как, нет. Ругался TS

2023-04-11 13:10 UTC, MikeDevice approved these changes

2023-04-12 08:56 UTC, MikeDevice commented
Смотри. Хочу небольшое тебе резюме составить. @artiquanta 

Глобально ты сделал всё очень круто! Видно, что у тебя горят глаза и ты хочешь сделать всё очень классно. Однако в данном ПР была допущена одна очень значительная ошибка –– ПР был очень большим и он включал в себя много оверхеда.

Твоя задача звучит, как "Вёрстка экрана начала игры" и в целом ты это и сделал, но помимо этого ты сделал ещё и другие экраны, как экран поиска игры, форму и тд и тп. Это сделало ПР монструозным и я прям офигел, когда увидел, сколько строк кода ты написал.

Так делать нехорошо. В реальных проектах такие штуки будут дорого обходиться, потому что на реальных проектах всё упирается в сроки, а такие огромные ПР -- это чёрный ящик: слишком долго ревьюится, слишком долго исправляется, слишком долго тестируется. И есть вероятность, что к моменту влития, возникнет мильён конфликтов с базовой веткой.

На будущее: если хочешь сделать больше, чем в задаче -- заводи дополнительные задачи и делай всё отдельными ПР, которые будут независимыми, маленькими и быстро вливаемыми.

2023-04-13 04:44 UTC, artiquanta commented
> Смотри. Хочу небольшое тебе резюме составить. @artiquanta
> 
> Глобально ты сделал всё очень круто! Видно, что у тебя горят глаза и ты хочешь сделать всё очень классно. Однако в данном ПР была допущена одна очень значительная ошибка –– ПР был очень большим и он включал в себя много оверхеда.
> 
> Твоя задача звучит, как "Вёрстка экрана начала игры" и в целом ты это и сделал, но помимо этого ты сделал ещё и другие экраны, как экран поиска игры, форму и тд и тп. Это сделало ПР монструозным и я прям офигел, когда увидел, сколько строк кода ты написал.
> 
> Так делать нехорошо. В реальных проектах такие штуки будут дорого обходиться, потому что на реальных проектах всё упирается в сроки, а такие огромные ПР -- это чёрный ящик: слишком долго ревьюится, слишком долго исправляется, слишком долго тестируется. И есть вероятность, что к моменту влития, возникнет мильён конфликтов с базовой веткой.
> 
> На будущее: если хочешь сделать больше, чем в задаче -- заводи дополнительные задачи и делай всё отдельными ПР, которые будут независимыми, маленькими и быстро вливаемыми.

Привет! Большое спасибо за ревью и дельные советы, учту!

2023-04-13 11:19 UTC, closed without merging

2023-04-13 11:33 UTC, MikeDevice commented
Чтоу??? Ты не стал вливать?

2023-04-13 17:28 UTC, artiquanta commented
> Чтоу??? Ты не стал вливать?

Влил, но через перезалив (другой веткой) без лишних изменений от преттиера и т.д., чтобы ребята могли спокойно своё влить без больших конфликтов. Цель была завершить работу над веткой sprint_5 и подтянуть все изменения в sprint_6. Цель достигнута. Влили все нужные изменения)