add hocAuth
Reactivnye-Enoty-Na-Lyzhan/among-us pull request #24
Opened 2023-04-12 07:30 UTC by KonstantinLanin

### Какую задачу решаем
Добавление HOC & hook для проверки авторизации

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-12 07:53 UTC, efremov-av commented on packages/client/src/store/auth/auth.slice.ts
> +    getUser: build.query<any, void>({
надо бы описать возвращаемый тип (убрать any)

2023-04-12 07:53 UTC, efremov-av commented on packages/client/src/hooks/useAuth.ts
> +  return data !== null && data !== undefined && data !== false && data !== 0 && data !== '';
можно узнать, а в чем разница с проверкой if (data) {} ?

2023-04-12 07:53 UTC, efremov-av commented on packages/client/src/hooks/useAuth.ts
> +  return data !== null && data !== undefined && data !== false && data !== 0 && data !== '';
и ожидается что getUser вернет объект юзера, так? зачем тогда проверять на строку и число? )

2023-04-12 08:01 UTC, KonstantinLanin commented on packages/client/src/hooks/useAuth.ts
> +  return data !== null && data !== undefined && data !== false && data !== 0 && data !== '';
Хотелось сделать сравнение строгим, чтобы data не была равна нул и/или андефайнд. Про проверку на число и строку можно сократить, согласен!

2023-04-12 08:04 UTC, KonstantinLanin commented on packages/client/src/store/auth/auth.slice.ts
> +    getUser: build.query<any, void>({
Ок, добавлю тип User

2023-04-12 08:23 UTC, efremov-av commented on packages/client/src/store/auth/auth.types.ts
> +  display_name: string;
у меня тут сомнения по поводу display_name и avatar, насколько я помню этих полей нет в форме регистрации и как следствие они будут пустые (null) после создания пользователя, но в документации Swagger указано что они string и required ) Это не замечание, а просто размышление! )

2023-04-12 09:59 UTC, efremov-av approved these changes
Все супер, единственное мне кажется все же надо добавить в тип user параметрам avatar и display_name типы null

2023-04-12 10:41 UTC, MikeDevice commented on packages/client/src/hooks/useAuth.ts
> +  return data !== null && data !== undefined && data !== false && data !== 0 && data !== '';
Не делай так больше никогда плиз)) Обычно же тебе нужно чтобы данные были объектом, так и проверяй на объект, а не на то, чего там не может быть. Это ненужный оверхед.

2023-04-13 10:08 UTC, MikeDevice requested changes
Всё ок, кроме хука

2023-04-13 10:08 UTC, MikeDevice commented on packages/client/src/hooks/useAuth.ts
> +  return data !== null && data !== undefined;
Есть вариант сделать так `return Boolean(data)` Проще и лаконичнее.

2023-04-13 10:08 UTC, MikeDevice commented on packages/client/src/hooks/useAuth.ts
> +export default useAuth;
что мне не нравится в этом хуке: он возвращает либо `true`, либо `false`, либо строку `'Loading'` -- это мега странно и неверно.

Основная претензия к строке. Потому что это тяжело поддерживать. Плюс, ты даже никак её не типизируешь. А если посмотришь на место использования хука, то там вообще игнорится строка:

```js
if (!isAuthenticated) {
  return <Navigate to="/login" />;
}
```

то есть переписав условие как

```js
if (isAuthenticated) {
   return <Page />
} else {
    return <Navigate to="/login" />;
}
```

Всё может пойти не по плану, так как `isAuthenticated` будет содержать не только данные "мы авторизовались", но и "сорян, я чё-то гружу"

2023-04-13 10:08 UTC, MikeDevice commented on packages/client/src/hooks/useAuth.ts
> +export default useAuth;
Вторая претензия -- не используешь типы TypeScript. Если бы ты параметризовал этот хук так, чтобы он явно возвращал `Boolean | 'Loading'`, то снаружи было бы меньше неявностей, но всё равно это не ок.

Идеально было бы возвращать два поля:

```
{ isAuthenticated, isLoading }
```

Тогда вся неявность бы ушла

2023-04-13 10:08 UTC, MikeDevice commented on packages/client/src/hoc/hocAuth.tsx
> +    return <Component />;
тут норм. доработай только хук. В нём отписал

2023-04-13 10:08 UTC, MikeDevice commented on packages/client/src/store/auth/auth.slice.ts
> +} = authApi;
вот это вообще огонь!

2023-04-13 10:08 UTC, MikeDevice commented on packages/client/src/store/auth/auth.types.ts
> +export type User = {
любопытства вопрос, а почему type, а не interface?

2023-04-14 09:29 UTC, MikeDevice approved these changes

2023-04-14 09:31 UTC, merged