Начало и завершение игры
Reactivnye-Enoty-Na-Lyzhan/among-us pull request #28
Opened 2023-04-14 11:41 UTC by artiquanta

### Какую задачу решаем
Реализовано начало и завершение игры.

**Примечание:** реализовано начало и завершение только оффлайн-режима игры (быстрая игра).

Остальные экраны начала игры и оптимизация текущих компонентов будут реализованы в рамках отдельных задач.

**Задача Linear:** REA-62

2023-04-14 13:55 UTC, Issayev approved these changes
Замечаний нет

2023-04-15 16:37 UTC, MikeDevice requested changes

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/store/game/game.types.ts
> +export type GameStageType = 'start' | 'preparing' | 'active' | 'finishing';
Если мы говорим о стадиях игры, то тогда не `start`, а `begining` и `activating`? Не уверен, что именно так, просто я пока не особо понимаю разнице между статусом и стадией? Разве это не одно и то же?

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/store/game/game.slice.ts
> +    result: 'lose',
как-то странно: игра только началась, а мы уже проиграли)) Может стоит ввести третий статус `init`? или лучше, наверное просто `null`

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/hooks/useActions.ts
> +  const dispatch = useDispatch<AppDispatch>();
👍

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/StartMenu/StartMenu.tsx
>    const handleStart = () => {
смотри. тут есть нарушение a11y (доступности). Ты делаешь кнопку ссылкой: в button передаёшь navigate. Собственно спрашивается, а почему тебе не заюзать ссылку?) Ведь это должно быть ссылкой)

В интернете много статей по этому поводу. Вот одна из https://htmlacademy.ru/blog/html/links-or-buttons.

Предлагаю не нарушать доступность и сделать

```jsx
<Link to={isOnline ? 'assembling' : 'preparing'}  onClick={startFastGame} />
```

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/StartMenu/StartMenu.tsx
> +  const isOnline = useTypedSelector(state => state.game.online);
А давай сделаем селектор `isOnlineSelector` и заюзаем его тут?

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +  const results = useTypedSelector(state => state.game.results);
Давай напишем селекторы? Наверняка, они будут переиспользоваться

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +  const { result, score } = results;
можно было бы на месте разобрать
```suggestion
  const { result, score } = useTypedSelector(state => state.game.results);
```

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +  const handleGameStart = useCallback(() => {
`GameEndButton` не обёрнут в `memo`, потому `useCallback` бессмысленен. Либо давай уберём, либо обернём

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/components/GameEndButton/GameEndButton.tsx
> +      evt.preventDefault();
ты это просто добавил или возникла необходимость?

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/components/GamePage/Game/Game.tsx
> +  const { finishGame } = useActions();
я что вдруг подумал. Я реально восхищаюсь этим вашим хуком. Он реально облегчает жизнь, но с другой стороны, добавляет неявности. Теперь, смотря на код, сложно сказать, какой метод является экшном, а какой -- просто функцией. Было бы классно, если бы все экшны имели наименования в стиле `someNameAction`, либо, чтоб этот хук отдавал объект со всеми экшонами `actions`.

не предлагаю менять, просто размышления

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/StartGame.tsx
> +        <Route path="await" element={<AwaitStart />} />
awaiting start :) нельзя в английском два глагола подряд)

2023-04-15 16:37 UTC, MikeDevice commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +  const [counter, setCounter] = useState<number>(startCooldown || 30);
хмм. два вопроса:
1. что за магическое число `30`? Тут лучше в константу вынести, чтобы было понятно, что оно значит, например `DEFAULT_COOLDOWN`.
2. А почему этот дефолт проставляется тут, а не в редаксе (в `initialStore`)?

2023-04-15 17:16 UTC, artiquanta commented on packages/client/src/store/game/game.types.ts
> +export type GameStageType = 'start' | 'preparing' | 'active' | 'finishing';
> Если мы говорим о стадиях игры, то тогда не `start`, а `begining` и `activating`? Не уверен, что именно так, просто я пока не особо понимаю разнице между статусом и стадией? Разве это не одно и то же?

Не, это сразу с заделом "на будущее", в мультиплеерные времена. Статус относится к "верхнеуровнему" определению состояния, а stage - подэтап статуса, текущий микрошаг.

2023-04-15 17:20 UTC, artiquanta commented on packages/client/src/store/game/game.slice.ts
> +    result: 'lose',
> как-то странно: игра только началась, а мы уже проиграли)) Может стоит ввести третий статус `init`? или лучше, наверное просто `null`

Это значение всегда перезаписывается в финале игры. Можно и null. А в чём будет разница, если фактически?  Есть только риск, что где-то что-то пойдёт не так, человек попадёт на нужную страницу и отловит падение? Компонент завершения игры не рассчитывает на другой вариант, кроме lose | win. Взято из готового компонента другого человека. 

Как ты в прошлый раз просил, не "вносил" все изменения разом, а сделал только "малую" задачу. Дальше - уже будет и оптимизация, и подгонка под реальные задачи.

2023-04-15 17:21 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/StartMenu/StartMenu.tsx
>    const handleStart = () => {
> смотри. тут есть нарушение a11y (доступности). Ты делаешь кнопку ссылкой: в button передаёшь navigate. Собственно спрашивается, а почему тебе не заюзать ссылку?) Ведь это должно быть ссылкой)
> 
> В интернете много статей по этому поводу. Вот одна из https://htmlacademy.ru/blog/html/links-or-buttons.
> 
> Предлагаю не нарушать доступность и сделать
> 
> ```js
> <Link to={isOnline ? 'assembling' : 'preparing'}  onClick={startFastGame} />
> ```

Сейчас экран отработан только для "демо". Дальше его логика будет иной. Я, конечно, могу перевести его в ссылку, а затем, уже в следующей задаче, возвращать всё обратно. Только вот зачем?

2023-04-15 17:23 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/StartMenu/StartMenu.tsx
> +  const isOnline = useTypedSelector(state => state.game.online);
> А давай сделаем селектор `isOnlineSelector` и заюзаем его тут?

Предлагаешь вынести только один для онлайна? Или плодить мильон + 1 селектор для каждого?
Кроме того, этот "функционал" после демо улетит далекооо и надолго.

2023-04-15 17:28 UTC, artiquanta commented on packages/client/src/components/GameEndButton/GameEndButton.tsx
> +      evt.preventDefault();
> ты это просто добавил или возникла необходимость?

Возникла необходимость. Чтобы не переделывать чужую работу в рамках своей "мелкой задачки".

2023-04-15 17:32 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/AwaitStart/AwaitStart.tsx
> +  const [counter, setCounter] = useState<number>(startCooldown || 30);
> хмм. два вопроса:
> 
> 1. что за магическое число `30`? Тут лучше в константу вынести, чтобы было понятно, что оно значит, например `DEFAULT_COOLDOWN`.
> 2. А почему этот дефолт проставляется тут, а не в редаксе (в `initialStore`)?

Это значение задаётся в initialStore. Уберу отсюда

2023-04-15 17:33 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/StartGame.tsx
> +        <Route path="await" element={<AwaitStart />} />
> awaiting start :) нельзя в английском два глагола подряд)

Здесь start - существительно

2023-04-15 17:36 UTC, artiquanta commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +  const handleGameStart = useCallback(() => {
> `GameEndButton` не обёрнут в `memo`, потому `useCallback` бессмысленен. Либо давай уберём, либо обернём

Опять же. Делал по твоей рекомендации. Не "делала в рамках не своей задачи". Это чужой компонент. В рамках этой задачи не стал переделывать. Сейчас переделаю

2023-04-15 17:54 UTC, artiquanta commented on packages/client/src/components/GamePage/Game/Game.tsx
> +  const { finishGame } = useActions();
Хорошо, обсудим с командой на следующей неделе!

2023-04-15 18:01 UTC, artiquanta commented on packages/client/src/store/game/game.slice.ts
> +    result: 'lose',
> как-то странно: игра только началась, а мы уже проиграли)) Может стоит ввести третий статус `init`? или лучше, наверное просто `null`

Значение перезаписывается в финале игры. Мелкая подстраховка. Компонент завершения игры дальше будет меняться. Сейчас этих изменений нет, чтобы "не делать лишнего в рамках малой задачи"

2023-04-15 18:02 UTC, artiquanta commented on packages/client/src/store/game/game.slice.ts
> +    result: 'lose',
Добавил 'init'

2023-04-15 18:02 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/StartMenu/StartMenu.tsx
>    const handleStart = () => {
Сделал ссылкой

2023-04-15 18:03 UTC, artiquanta commented on packages/client/src/components/GamePage/Game/Game.tsx
> +  const { finishGame } = useActions();
> я что вдруг подумал. Я реально восхищаюсь этим вашим хуком. Он реально облегчает жизнь, но с другой стороны, добавляет неявности. Теперь, смотря на код, сложно сказать, какой метод является экшном, а какой -- просто функцией. Было бы классно, если бы все экшны имели наименования в стиле `someNameAction`, либо, чтоб этот хук отдавал объект со всеми экшонами `actions`.
> 
> не предлагаю менять, просто размышления

Хорошо, обсудим с командой на неделе!

2023-04-15 18:11 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/StartMenu/StartMenu.tsx
> +  const isOnline = useTypedSelector(state => state.game.online);
> А давай сделаем селектор `isOnlineSelector` и заюзаем его тут?

Можно, но в рамках другой задачи.

2023-04-15 18:15 UTC, artiquanta commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +  const results = useTypedSelector(state => state.game.results);
Хорошо, но не в рамках этой задачи

2023-04-15 19:35 UTC, artiquanta commented on packages/client/src/components/GamePage/StartGame/StartMenu/StartMenu.tsx
> +  const isOnline = useTypedSelector(state => state.game.online);
> А давай сделаем селектор `isOnlineSelector` и заюзаем его тут?

Добавил два селектора, не мемоизированных. Если будет необходимость, добавим дополнительный. Селектор для каждого поля добавлять не стал - плохая практика.

2023-04-17 08:10 UTC, MikeDevice commented on packages/client/src/components/GameEndButton/GameEndButton.tsx
> +      evt.preventDefault();
Не скажу, что задача мелкая))

2023-04-17 08:10 UTC, MikeDevice approved these changes

2023-04-19 07:55 UTC, merged