Feature/rea 27
Reactivnye-Enoty-Na-Lyzhan/among-us pull request #31
Opened 2023-04-17 18:34 UTC by Issayev

# Добавление логики регистрации

![signup](https://user-images.githubusercontent.com/32362017/232579390-648329bb-36a7-49de-bfff-d3cb88c11511.png)

2023-04-18 04:32 UTC, artiquanta commented on packages/client/src/components/SignUpPage/Form.tsx
> +import { useNavigate } from 'react-router-dom';
Давай сделаем так, чтобы библиотеки импортировались в самом начале

2023-04-18 04:34 UTC, artiquanta commented on packages/client/src/components/SignUpPage/Form.tsx
> +  const valuesRef = useRef(values);
Для чего Ref? Здесь можно обойтись без них

2023-04-18 05:42 UTC, artiquanta requested changes
Работы ты проделал много!
Но почему-то ты снова пошёл по пути тотального усложнения и в итоге чуть не в ту сторону ушёл.

Основные комментарии отписал, также постарайся избавиться от приведения типов, где это возможно. После исправлений, вероятно, у тебя не будет мест, где это приведение может понадобиться!

**Важный момент:** сейчас при положительном исходе пробрасывает на страницу входа. Попробовал с 3 браузеров, как в режиме инкогнито, так и без.

Спасибо, что исправил мою опечатку в font.css.

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/components/SignUpPage/_types.d.ts
> +export type SignUpFormData = {
Декларации используются для другого. Переделай в .types.ts. [Про декларации]( https://scriptdev.ru/guide/058/#declaration)

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/services/signup/_types/index.d.ts
> +export type SignUpRequestDTO = {
Переделай в .types.ts

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/components/SignUpPage/Form.tsx
> +      setSignupQueryError(
Сообщение об успехе - не сообщение об ошибке. Также используй [это](https://redux-toolkit.js.org/rtk-query/usage/queries#frequently-used-query-hook-return-values)

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/components/SignUpPage/Form.tsx
> +    try {
Не нужно хранить весь функционал в одно месте. Разбей код на разные функции, соответствующие своей задаче. Каждая функция должна отвечать только за конкретную задачу.

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/components/SignUpPage/Form.tsx
> +    if (getUserQueryStatus.isSuccess) {
Нет нужды в задержках, особенно таких длинных. Если всё успешно - круто, выводи сразу сообщение об успешной регистрации. И уже после этого делай остальные проверки и перенаправляй пользователя. Если всё произойдёт молниеносно - тем ещё лучше.

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/components/SignUpPage/Form.tsx
> +      <div className="signup-page-main__api_error">{signupQueryError}</div>
**Можно лучше:** здесь ты, вероятно, опечатался и сделал элемент не элементом, а модификатором (элемент api, модификатор error булевого типа)

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/components/SignUpPage/Form.tsx
> +    const data = transformFormDataToDTO(valuesRef.current as SignUpFormData);
А зачем, если у тебя все данные в values?

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/components/SignUpPage/_utils/transformFormDataToDTO.ts
> +export function transformFormDataToDTO(
Есть ли в этом необходимость?

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/services/signup/error-message/enum-api-errors.ts
> +
Чётенько! :)

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/components/SignUpPage/Form.tsx
> +      const signupResponse = await SignUpService.signup(data);
**Исправить:** почему не через RTK Query?

2023-04-18 05:42 UTC, artiquanta commented on packages/client/src/components/SignUpPage/SignUpPage.css
> +.signup-page-main__api_error {
**Можно лучше:** размер текста сообщения и цвет для "положительного" результата не соответствуют макету.

2023-04-18 06:34 UTC, Issayev commented on packages/client/src/components/SignUpPage/Form.tsx
> +  const valuesRef = useRef(values);
Это нужно, чтобы использовать useCallback  на onSubmitHandler

2023-04-18 06:43 UTC, Issayev commented on packages/client/src/components/SignUpPage/Form.tsx
> +import { useNavigate } from 'react-router-dom';
Честно говоря, неудобно руками переставлять импорты каждый раз. Может все же подключить плагин для eslint?

2023-04-18 06:51 UTC, Issayev commented on packages/client/src/components/SignUpPage/Form.tsx
> +    const data = transformFormDataToDTO(valuesRef.current as SignUpFormData);
Хочу использовать useCallback. Если просто values передать, то он запомнит только начальное состояние, если добавить values в dependencies, много смысла не будет, т.к функция будет пересоздаваться с каждой введенной буквой. Я сылшал есть хук useEffectEvent для таких целей, но он не реализован до конца в React

2023-04-18 06:52 UTC, Issayev commented on packages/client/src/components/SignUpPage/_types.d.ts
> +export type SignUpFormData = {
Поправил [3463a1b](https://github.com/Reactivnye-Enoty-Na-Lyzhan/among-us/pull/31/commits/3463a1bfdfa8788b7a6bcf07eb42bcca2d058d61)

2023-04-18 06:52 UTC, Issayev commented on packages/client/src/services/signup/_types/index.d.ts
> +export type SignUpRequestDTO = {
Поправил [3463a1b](https://github.com/Reactivnye-Enoty-Na-Lyzhan/among-us/pull/31/commits/3463a1bfdfa8788b7a6bcf07eb42bcca2d058d61)

2023-04-18 06:57 UTC, Issayev commented on packages/client/src/components/SignUpPage/_utils/transformFormDataToDTO.ts
> +export function transformFormDataToDTO(
В функции transform? Думаю, есть. В апишных json'ах имена полей часто не соответсвую стилю camelCase. Тут, кончено простой случай. Мне кажется, это можно отнести к частному случаю работы с DTO

2023-04-18 07:15 UTC, artiquanta commented on packages/client/src/components/SignUpPage/Form.tsx
> +  const valuesRef = useRef(values);
> Это нужно, чтобы использовать useCallback на onSubmitHandler

Компонент формы - не memo, более того, твой onSubmit он потом ещё и инлайнит.

Какой выигрыш от подобной оптимизации с учётом того, что сложность кода возросла (ты сделал много доп. вещей)?

2023-04-19 09:01 UTC, artiquanta commented on packages/client/src/vendor/fonts/fonts.css
> +    url(.//Inter/Inter-Medium.woff) format('woff');
//

2023-04-19 10:17 UTC, artiquanta approved these changes

2023-04-19 12:18 UTC, merged