Feature/rea 14
Reactivnye-Enoty-Na-Lyzhan/among-us pull request #4
Opened 2023-03-28 12:28 UTC by Issayev

Начальная версия лэндинга

2023-03-28 13:37 UTC, artiquanta commented on packages/client/package.json
> +  "license": "MIT",
**Можно лучше:** предлагаю восстановить первичный порядок -  project info - scripts - dependecines, devDependencies. Очень хорошо, что отсортировал всё зависимости по имени.

2023-03-28 13:50 UTC, Issayev commented on packages/client/package.json
> +  "license": "MIT",
7130ad1f913c2b50eda16033477f8e0efea2b548 вернул старый порядок

2023-03-29 14:16 UTC, Issayev commented
Исправил основные замечания

2023-03-30 04:46 UTC, KetiRudneva approved these changes
Критических замечаний нет

2023-03-30 04:47 UTC, KonstantinLanin approved these changes
Критических замечаний нет

2023-03-30 04:50 UTC, artiquanta commented
> Критических замечаний нет

А есть ли рекомендации для него, что можно сделать лучше?

2023-03-30 05:04 UTC, KonstantinLanin commented
> 

Что можно сделать лучше на мой взгляд: 
- Зафиксировать версии в package.json
- Добавить настройку 'autoprefixer' в плагин 'postcss-preset-env', чтобы добавлять префиксы к свойствам для совместимости с разными браузерами
- Добавлять в footer картинки через background-image (можем уменьшить размер бандла)

2023-03-30 05:19 UTC, Issayev commented
> > 
> 
> Что можно сделать лучше на мой взгляд:
> 
>     * Зафиксировать версии в package.json
> 
>     * Добавить настройку 'autoprefixer' в плагин 'postcss-preset-env', чтобы добавлять префиксы к свойствам для совместимости с разными браузерами
> 
>     * Добавлять в footer картинки через background-image (можем уменьшить размер бандла)

2023-03-30 07:45 UTC, MikeDevice requested changes

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/postcss.config.js
> +
почему выпилили плагины, которые тут были? вам не нужны импорты и преффиксы?

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/Footer/Footer.css
> +  height: var(--footer-height);
дубль

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/Footer/Footer.css
> +    -webkit-user-drag: none;
а для чего потребовалось?

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/images/landing-page/icons/react-logo.svg
все svg должны быть пожаты через svgo

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/images/landing-page/wallpapers/1.png
1. Почему все png пустые?
<img width="636" alt="image" src="https://user-images.githubusercontent.com/7154108/228757736-a6372a79-b57a-4074-a3cf-6373298ade60.png">

2. Нет 2х картинок для ретины https://htmlacademy.ru/blog/html/retina

3. Все png должны быть так же пожаты как и svg только через тулзу для png, например https://tinypng.com

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/vendor/styles/normalize.css
А почему скопипастил в истодники? Почему бы не сделать import из `node_modules`. Нормазайзер же -- обычная зависимость

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/vite.config.ts
> +console.log(outputNamesOptions);
логи оставлять не надо

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/vite.config.ts
> +}
А зачем? Просто интересно. Вит же по дефолту умеет всё по красоте. Расскажешь?

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/vite.config.ts
> +    cssMinify: false,
а зачем выключил? В проде то всё пожато должно быть

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/Main/game-description-text.ts
> +export default `
А почему ты так сделал? А не просто в вёрстке текст?

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/Header/Header.css
> +  max-height: 12vh;
ты всё сверстал на vh, vw. Ты уверен, что оно действительно тебе нужно и в дальнейшем ничего не развалится?

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/Header/Header.tsx
> +        </svg>
Мощно. Расскажи плиз, какую цель ты тут преследуешь, и почему пришлось сделать именно так?

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/LandingPage.tsx
> +      <PageFooter></PageFooter>
Можно короче

```diff
- <PageWallpaper></PageWallpaper>
- <PageHeader></PageHeader>
- <PageMain></PageMain>
- <PageFooter></PageFooter>
+ <PageWallpaper />
+ <PageHeader />
+ <PageMain />
+ <PageFooter />
```

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/LandingPage.tsx
> +import './LandingPage.css';
стили правильнее всего подключать в конце всех импортов, чтобы порядок в цсс был верный

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/LandingPage.tsx
> +import './LandingPage.css';
Потому что сейчас у тебя стили Main и PageWallpaper будут объявлены ниже, оттого вес их будет выше, и в дальнейшем тебе придётся их перебивать

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/Main/Main.tsx
> +        <a href="#" className="game-description__join-link">
а дальнейшем ссылку поменяете же? тут не будет хэша? Это временное?

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/Wallpaper/Wallpaper.css
> +  @for $i from 1 to 8 {
программирование на цсс))

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/Wallpaper/Wallpaper.css
> +  *[class^='background-wallpaper__stars'] {
зачем так сложно? Просто повесь этим картинкам доп. класс, у которого будут эти стили.

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/iconfont/fonts.css
> +}
этот файл ты откуда-то взял? Расскажи мотивациию того, что тут делаешь.

2023-03-30 07:45 UTC, MikeDevice commented on packages/client/src/components/LandingPage/Header/Header.css
> +  max-height: 12vh;
мне кажется тут зашли бы гриды, но дело твоё

2023-03-30 07:46 UTC, MikeDevice commented
Настройте Версель, чтоб можно было посмотреть вживую, что сделано

https://github.com/Reactivnye-Enoty-Na-Lyzhan/among-us#автодеплой-статики-на-vercel

2023-03-30 08:15 UTC, Issayev commented on packages/client/postcss.config.js
> +
автопрефиксер включен в postcss-preset-env;
postcss-import включен в vite

2023-03-30 08:22 UTC, Issayev commented on packages/client/src/images/landing-page/wallpapers/1.png
1. они не пустые, просто там изображения белым цветом
![wallpaper](https://user-images.githubusercontent.com/32362017/228775137-d8faf2eb-fa78-44d0-9004-9a7956fcb234.png)
2. добавил 2х изображения 1522ace и стили к ним 462bf79
3. сжал изображения 69dfe5125b249227ab96aca136e9ecfa4745fce1

2023-03-30 08:29 UTC, Issayev commented on packages/client/src/components/LandingPage/Footer/Footer.css
> +  height: var(--footer-height);
поправил 53a367d3b197f3e31c9e7fe101d8f9640541e78b

2023-03-30 08:30 UTC, Issayev commented on packages/client/src/components/LandingPage/Main/Main.tsx
> +        <a href="#" className="game-description__join-link">
Да, далее исправлю на страницу входа

2023-03-30 08:30 UTC, Issayev commented on packages/client/src/components/LandingPage/Wallpaper/Wallpaper.css
> +  @for $i from 1 to 8 {
ну показалось, восемь раз копировать излишне)

2023-03-30 08:35 UTC, Issayev commented on packages/client/src/components/LandingPage/Footer/Footer.css
> +    -webkit-user-drag: none;
Возможно, не нужно. Просто заметил, что появляется как бы открепленная копия картинки, если зажать курсор и перетаскивать

2023-03-30 08:38 UTC, Issayev commented on packages/client/src/images/landing-page/icons/react-logo.svg
использовал три штуки, все пожаты должны быть. Postcss иконка много весит, меньшего размера не удалось найти - в ней много деталей, может в этом дело

2023-03-30 08:46 UTC, Issayev commented on packages/client/src/components/LandingPage/Wallpaper/Wallpaper.css
> +  *[class^='background-wallpaper__stars'] {
добавил дополнительный класс 529c856c9b489fb25098542a4e2eeede8dba831c

2023-03-30 09:12 UTC, Issayev commented on packages/client/src/components/LandingPage/iconfont/fonts.css
> +}
этот файл сгенерирован вместе с иконочным шрифтом.  Решил создать шрифт для иконки гитхаба. Мотивация: вставлять иконку как часть текста. В данном случае показалось удобным выставление  размера  через font-size, а также она подчеркивается, как и название ссылки.

2023-03-30 09:14 UTC, Issayev commented on packages/client/src/components/LandingPage/LandingPage.tsx
> +import './LandingPage.css';
Поправил 0cf82dee8a4c4726c51285b5d42a247868e2e7db

2023-03-30 09:28 UTC, Issayev commented on packages/client/src/images/landing-page/icons/react-logo.svg
все же прогнал через оптимайзер 69dfe5125b249227ab96aca136e9ecfa4745fce1
размер двух уменьшился, хотя на сайте https://www.svgrepo.com/ , откуда брал иконки, написано, что оптимизированы

2023-03-30 11:45 UTC, MikeDevice commented
выглядит красиво. сюда бы шрифтец какой-нить топовый https://among-us-client-git-feature-rea-14-reactive-enoty.vercel.app/

2023-03-30 11:48 UTC, MikeDevice approved these changes

2023-03-30 14:33 UTC, merged