add validation feature to form component
Reactivnye-Enoty-Na-Lyzhan/among-us pull request #5
Opened 2023-03-28 16:33 UTC by efremov-av

### Какую задачу решаем
Создал хук валидации формы useValidation он принимает в себя массив филдов с функциями проверки.
Добавил в utils функции валидации которые были использованы в предыдущем модуле.
Добавил в компонент Input текст валидации и добавил модификатор _invalid который красит компонент согласно макету.

### Скриншоты/видяшка (если есть)
![Снимок экрана 2023-03-28 в 23 32 57](https://user-images.githubusercontent.com/98008460/228307781-26649c21-88c9-4c3e-86fe-3f5bad86b515.png)

### TBD (если есть)

2023-03-29 07:09 UTC, artiquanta requested changes
В целом, работа проделана хорошая. Понравилась идея с добавление кастомных сообщений об ошибках)

**Нужно исправить:** состояние валидации input'а не сбрасывается после нового ввода (события input) пользователем. Сообщения валидации, соответственно, не изменяются.

**Можно лучше**: hook валидации рекомендую перенести в src/hooks, чтобы иметь возможность использовать его для других форм. 

**Замечания по компоненту формы в целом:**
1. Ширина формы при ширине вьюпорта в 1280 - 300px;
2. Расстояние между input'ами - 34 (35) px.
3. Cообщения об ошибках не должны раздвигать форму. Ничего не должно скакать.
4. Глазик для отображения пароля должен появляться, только когда поле ввода пароля в фокусе.
5. Кнопка - элемент формы. Как и поле для сообщений об ошибке или успехе в форме.

**Советы по БЭМ:**
1. У Блока не может быть каких-либо внешних стилей, которые позиционирует его относительно документа или других элементов.

**Пример:** в твоём случае у Блока **form-input** есть margin. Если тебе нужно добавить Блоку внешние отступы - используй для этого модификатор Блока: **form-input form-input_spacing_outer** Или же миксы: **form-input form__form-input**

2. В БЭМ стилизация элементов происходит по классу (не по тегу). Т.е. если ты хочешь стилизовать какой-то элемент, то правильней будет ему добавить класс и описать все стили там.

3. Скорее всего, лучше не описывать стиль так, чтобы все элементы блока и их модификаторы визуально были вложены в один блок объявления (https://disk.yandex.ru/i/ESCLtqeL5qU6VQ). Если хочешь, то можно использовать вложенность для псевдоклассов и псевдоэлементов. Читаемость повысится. **С другой стороны, можно повторно обсудить данный момент с командой**

2023-03-29 18:25 UTC, efremov-av commented
Исправил все замечания.
Единственное, видимость "глазика" сделал через hover, так как если использовать focused на input, при нажатии на сам "глазик" теряется фокус.

2023-03-30 17:10 UTC, efremov-av commented
Добавил live валидацию поля формы на потерю фокуса, слегка подправил стили и отсортировал файлы в проекте.

2023-03-31 06:21 UTC, artiquanta commented on packages/client/src/components/Form/Input/Input.css
> +    border-bottom: 1px solid #e0d700 !important;
**Можно лучше:** постараться свести на минимум использование !important и совмещение в селекторе тега и класса ([ссылочка на БЭМ](https://ru.bem.info/methodology/css/#%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%B5%D0%B3%D0%B0-%D0%B8-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0-%D0%B2-%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B5))

[Про !important, специфичность и каскад на MDN](https://developer.mozilla.org/ru/docs/Web/CSS/Specificity)

2023-03-31 06:32 UTC, artiquanta approved these changes
Критических замечаний нет. Шрифты отдельно подключим в src/vendor/fonts

2023-03-31 17:31 UTC, MikeDevice requested changes

2023-03-31 17:31 UTC, MikeDevice commented on packages/client/src/components/Form/Button/Button.tsx
> +const Button: FC<Props> = ({ text, disabled }: Props) => {
когда у тебя используется `FC`, то пропсы типизовать уже не надо:

```diff
- Button: FC<Props> = ({ text, disabled }: Props)
+ Button: FC<Props> = ({ text, disabled })
```

2023-03-31 17:31 UTC, MikeDevice commented on packages/client/src/components/Form/Form.tsx
> +const Form: FC<Props> = ({ children, onSubmit }: Props) => {
то же, что и выше

2023-03-31 17:31 UTC, MikeDevice commented on packages/client/src/components/Form/Input/Input.tsx
> +        validation?.isValid === false ? 'form-input_invalid' : ''
поставь либу classnames, не страдай)

2023-03-31 17:31 UTC, MikeDevice commented on packages/client/src/utils/validation.ts
> +};
1. в методах копипаста текстов. Нужно вынести тексты в конфиг/константы.
2. Некоторые валидации повторяются: на длину или отсутствие -- сделай отдельные методы для этого, чтоб не дублировать логику.

2023-03-31 17:31 UTC, MikeDevice commented on packages/client/src/hooks/useValidation.ts
> +    return !newValidationData.some(v => v.isValid === false);
```diff
- v => v.isValid === false
+ v => !v.isValid
```

2023-03-31 17:31 UTC, MikeDevice commented on packages/client/src/components/LoginPage/LoginPage.tsx
> +    <div style={{ backgroundColor: '#010318', width: '100%', padding: '40px' }}>
не инлайнь стили

2023-03-31 17:31 UTC, MikeDevice commented on packages/client/src/components/LoginPage/LoginPage.tsx
> +          validation={validationData.find(v => v.field === 'password')}
не круто так делать. у тебя на каждый рендер будет для каждого поля формы делаться проход по циклу. Рендер становится капец каким медленным. Найди все валидаторы в самом начале и сложи их в мемо, или же не держи их в массиве, а в объекте, тогда поиск будет всегда О(1)

2023-03-31 18:44 UTC, efremov-av commented on packages/client/src/utils/validation.ts
> +};
Не совсем понял второй пункт, можно подробнее его описать?

2023-03-31 22:17 UTC, MikeDevice commented on packages/client/src/utils/validation.ts
> +};
ну смотри.

вот у тебя сейчас есть дубли в login и password и ещё где-то, где ты проверяешь на пустую строку:

```
if (!value) text = 'Поле не может быть пустым';
```

это копипаста, которой быть не должно.

В идеале у тебя должны быть функции примитивы:
```
// validation-helpers.ts

export isEmpty = ...
export min = ...
export max = ...
...
```

В этих хелперах и будут зашиты все твои тексты и проверки. Таким образом твоя валидация уже не будет копипастой с текстами.

а вообще рекомендуйю посмотреть на yup. Зачем городить свои велосипеды?) https://github.com/jquense/yup

2023-03-31 22:28 UTC, MikeDevice commented on packages/client/src/utils/validation.ts
> +};
ну и смотри какая вторая проблема -- огромные ифаки. Смотри, как бы круто сделать:

```
name: (v) => [notEmpty, checkLangs, firstCapitalLetter]
name: (v) => [notEmpty, email],
login: (v) => [notEmpty, length(3, 20), bannedSymbols, noSpace, langs, onlyNumbers]
```

Ты вот так описываешь схему и всё красиво и элегантно, а под капотом это работает примерно так:

когда нужно проверить валидацию имени:

```
// вызов
name('lololo')

// строка 'lololo' последовательно передаётся в каждую из функций [notEmpty, checkLangs, firstCapitalLetter].
// Какая функция упала -- тот текст и показали. Если ничего не упало -- валидация пройдена
```

2023-03-31 22:33 UTC, MikeDevice approved these changes
в целом ок. если хочется сделать лучше -- сделай валидацию круче, убрав ифаки и удалив инлайновые стили.

2023-03-31 22:33 UTC, MikeDevice commented on packages/client/src/components/LoginPage/LoginPage.tsx
> +        padding: '40px',
инлайнить стили не надо. вынести в цсс

2023-04-01 14:19 UTC, merged

2023-04-01 14:19 UTC, efremov-av commented on packages/client/src/components/LoginPage/LoginPage.tsx
> +        padding: '40px',
это временная страница, задача ее сверстать не моя, поэтому я заинлайнил стили чтобы было где продемонстрировать форму )