Feature/REA-106
Reactivnye-Enoty-Na-Lyzhan/among-us pull request #53
Opened 2023-05-01 06:16 UTC by KonstantinLanin

### Какую задачу решаем
Добавление OAuth-авторизации

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-04 15:30 UTC, artiquanta approved these changes
Хорошая работа! :)

2023-05-05 10:50 UTC, MikeDevice requested changes

2023-05-05 10:50 UTC, MikeDevice commented on packages/client/src/utils/oauth/redirectToOAuthYandex.ts
> +  window.location.href = `${url}?${params}`;
лучше использовать `location.assign`, как минимум тесты потом проще будет писать

https://stackoverflow.com/questions/10302905/location-href-property-vs-location-assign-method

2023-05-05 10:50 UTC, MikeDevice commented on packages/client/src/utils/oauth/getRedirectUrl.ts
> +  }
так. тут что-то нездоровое происходит и вот почему. ты явно зашиваешь домены, на которых будет раскатываться этот код. Следовательно, если придётся менять домен, то и придётся менять код. Привет Принцип Открытости-Закрытости и Плохо пахнущий код.

2023-05-05 10:50 UTC, MikeDevice commented on packages/client/src/utils/oauth/getRedirectUrl.ts
> +  }
по идее мы же можем в коде узнать домен и подставить его в редирект, разве нет?

2023-05-05 10:50 UTC, MikeDevice commented on packages/client/src/components/LoginPage/LoginPage.tsx
> +    }
это бизнес логика, которая должна быть в контроллере, а не во вьюхе. Компонент -- это вьюха. Не рушь методологии дедов))

2023-05-05 10:50 UTC, MikeDevice commented on packages/client/src/components/LoginPage/LoginPage.tsx
> +  }, [searchParams]);
тут то же, что и выше

2023-05-12 09:15 UTC, MikeDevice requested changes

2023-05-12 09:15 UTC, MikeDevice commented on packages/client/src/hooks/useOAuth.ts
> +      }).unwrap();
так. `unwrap` -- это какой-то костыль. рассказывай зачем делаешь? Ошибку так пытаешься отловить?

2023-05-12 10:21 UTC, KonstantinLanin commented on packages/client/src/hooks/useOAuth.ts
> +      }).unwrap();
Чтобы получить ответ и вернуть как обычное значение, чтобы его можно было использовать дальше. Не верно?

2023-05-12 10:25 UTC, MikeDevice commented on packages/client/src/hooks/useOAuth.ts
> +      }).unwrap();
аааа. всё, сорян, я неправильно понял.

2023-05-12 10:26 UTC, MikeDevice approved these changes

2023-05-12 10:35 UTC, merged