Feature/rea 123
Reactivnye-Enoty-Na-Lyzhan/among-us pull request #59
Opened 2023-05-23 08:06 UTC by KonstantinLanin

### Какую задачу решаем
API форума

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-23 10:23 UTC, artiquanta requested changes
Ожидаем исправлений!

2023-05-24 08:37 UTC, artiquanta approved these changes
Красота :)

Теперь я точно создам тему на форуме с просьбой добавить тему оформления с енотиками!

Пока что только на бэкенде, но мы уже близко!

2023-05-26 12:39 UTC, MikeDevice approved these changes
Все очень просто, и это круто. простой код -- лучший код. Но я бы сделал небольшое улучшение. Ты в каждой ручке делаешь try catch, это копипаста, которая неприятна. В идеале было бы круто сделать базовую ручку, у который был бы try catch, а все остальные просто бы юзали его:

App.get(/users, withErrorHandler(() => { ... })

2023-05-28 07:35 UTC, MikeDevice approved these changes
я же уже аппрувнул) мог не перезапрашивать)

2023-05-30 12:33 UTC, merged