add end game page
Reactivnye-Enoty-Na-Lyzhan/among-us pull request #6
Opened 2023-03-29 15:25 UTC by KonstantinLanin

### Какую задачу решаем
Вёрстка экрана завершения игры

### Скриншоты/видяшка (если есть)
<img width="1372" alt="Снимок экрана 2023-03-29 в 18 22 43" src="https://user-images.githubusercontent.com/122603454/228588048-921b6db2-cc1a-4060-882b-faafdfe16343.png">

### TBD (если есть)

2023-03-30 02:44 UTC, Issayev requested changes

2023-03-30 02:44 UTC, Issayev commented on packages/client/src/components/GameEndButton/GameEndButton.tsx
Может лучше добавить типизацию props?

2023-03-30 02:44 UTC, Issayev commented on packages/client/src/fonts/Inter-Bold.woff
Договорились, что шрифты лежат в vendor/fonts . Еще бы я создал отдельную папку для Inter: vendor/fonts/Inter

2023-03-30 02:44 UTC, Issayev commented on packages/client/src/components/GamePage/GamePage.tsx
посмотрел result='lose'. У меня как-то заголовок отображается на нескольких строках. Также при скролле страницы нижняя часть белым цветом.
![gameEndLose](https://user-images.githubusercontent.com/32362017/228712155-44062621-38ac-4bf9-b539-776eb4024e8a.png)

2023-03-30 02:44 UTC, Issayev commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +import impostorOne from '../../images/impostor-yellow.svg';
Я бы импортировл через vite alias.  
Я у себя сделал alias на images 03f437e78a905a9a53891d4730d0b7e53cab4a91 , чтобы можно было импортировать from 'images/...'

2023-03-30 02:44 UTC, Issayev commented on packages/client/src/images/impostor-dead.svg
Возможно стоит сгруппировать добавленные изображения в отдельную папку внутри images. Думаю, в будущем их будет много

2023-03-30 02:44 UTC, Issayev commented on packages/client/src/utils/variables.css
Переменные из этого файла нигде не ипользуются. Если предполагалось подключить в общие стили, можно более уточнающие имена

2023-03-30 05:33 UTC, KonstantinLanin commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +import impostorOne from '../../images/impostor-yellow.svg';
Посмотрел на твою реализацию. Добавил ✔️

2023-03-30 05:34 UTC, KonstantinLanin commented on packages/client/src/images/impostor-dead.svg
Согласен

2023-03-30 07:32 UTC, KonstantinLanin commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +import impostorOne from '../../images/impostor-yellow.svg';
И убрал) добавил изображения через фон

2023-03-30 08:04 UTC, Issayev approved these changes
Верстка в варианте проигрыша поправлена. Шрифты и изображения перенесены в нужные папки. В целом, хорошо

2023-03-30 11:49 UTC, MikeDevice requested changes
Не зови смотреть, пока CI не будет зелёным

2023-03-30 12:24 UTC, MikeDevice requested changes

2023-03-30 12:24 UTC, MikeDevice commented on packages/client/src/App.css
> +  font-family: Inter;
нужны фолбэки шифтов

2023-03-30 12:24 UTC, MikeDevice commented on packages/client/src/App.css
> +  font-family: Inter;
https://htmlacademy.ru/blog/html/fonts-loading

2023-03-30 12:24 UTC, MikeDevice commented on packages/client/src/components/GameEnd/GameEnd.css
> +  position: absolute;
у кого будет relative? у контейнера его нет. тут можешь словить весёлых багов

2023-03-30 12:24 UTC, MikeDevice commented on packages/client/src/components/GameEnd/GameEnd.css
> +  background-image: url(../../images/game-end/impostor-yellow.svg);
затащить 2х-картинки для ретины. Смотри на соседний ПР, там уже это есть

2023-03-30 12:24 UTC, MikeDevice commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +export default function GameEnd({result, score}: Props){
лучше тут юзать тип React.FunctionComponent

2023-03-30 12:24 UTC, MikeDevice commented on packages/client/src/components/GamePage/GamePage.tsx
> +export default function GamePage() {
почему не юзаете ТС с типами?

2023-03-30 12:24 UTC, MikeDevice commented on packages/client/src/components/GameEndButton/GameEndButton.tsx
> +        className={`game-end__button-name game-end__button-name_${props.color} game-end__button-name_spacing_below`}>
установи либу classnames

2023-03-30 12:24 UTC, MikeDevice commented on packages/client/src/components/GameEndButton/GameEndButton.tsx
> +        onClick={handleClick}
кнопки с навигацией -- зло. это должна быть ссылка (Link из react-router)

2023-03-30 12:24 UTC, MikeDevice commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +  }
ифаки -- зло. Сделай хэш:

```
config = {
  lose: ...
  win: ...
}

imageRightSrc = config[result].right
```

Выше -- просто пример. Но подумай в этом направлении

2023-03-30 12:24 UTC, MikeDevice commented on packages/client/src/images/game-end/impostor-yellow.svg
пожать все картинки

2023-03-30 12:34 UTC, KonstantinLanin commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +export default function GameEnd({result, score}: Props){
Чем лучше?

2023-03-30 12:55 UTC, MikeDevice commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +export default function GameEnd({result, score}: Props){
Ну давай посмотрим)

вот пример https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecBiAwnAL5wBmUEIcA5FKhrQFDMwCeYScAClWAGdczOHBjAYAGyQAuOAJhRgAOwDmAbmYlW5AK7KMwCMrgBBABR5xU7iTl8IggJTDRDGLqgnr0uAH44AB4AE2AANzgAegA+ODkARgAGRK1WNGMFOAAhOSJAh0FYgF44SzEJXxIXIticETh3T28K7gCQ8KjYhOStIA

Из примера выше видно, что компонент B не пропускает невалидный тип, и компиляция ломается.

Всё дело в том, что тут ты просто объявляешь тип пропсов, а FC ещё всякую внутрянку делает, в том числе и объявляя тип результата

2023-03-30 12:55 UTC, MikeDevice commented on packages/client/src/components/GameEnd/GameEnd.tsx
> +export default function GameEnd({result, score}: Props){
<img width="687" alt="image" src="https://user-images.githubusercontent.com/7154108/228842637-b1952eea-22c2-4bdf-b812-97c5410ee233.png">

2023-04-01 03:36 UTC, KonstantinLanin commented on packages/client/src/images/game-end/impostor-yellow.svg
http://joxi.ru/zANKvMQhwy97pr

2023-04-01 03:43 UTC, KonstantinLanin commented on packages/client/src/components/GameEndButton/GameEndButton.tsx
> +        className={`game-end__button-name game-end__button-name_${props.color} game-end__button-name_spacing_below`}>
Почему лучше использовать библиотеку classnames?

2023-04-01 03:53 UTC, KonstantinLanin commented on packages/client/src/components/GameEnd/GameEnd.css
> +  position: absolute;
У класса game

2023-04-01 06:57 UTC, MikeDevice commented on packages/client/src/components/GameEndButton/GameEndButton.tsx
> +        className={`game-end__button-name game-end__button-name_${props.color} game-end__button-name_spacing_below`}>
можешь не использовать. но с ней проще, когда классны начнут разрастаться и начнут появляться условные классы

2023-04-02 14:14 UTC, MikeDevice requested changes
Решить конфликты

2023-04-03 06:28 UTC, MikeDevice approved these changes

2023-04-07 03:17 UTC, merged